name: TurtleBot3c Ubuntu Core image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  turtlebot3c-pi-gadget-snap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build snap
        id: build-snap
        uses: snapcore/action-build@v1
        with:
          path: pi-gadget
      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: turtlebot3c-pi-gadget-snap
          path: ${{ steps.build-snap.outputs.snap }}
  ubuntu-image:
    runs-on: ubuntu-latest
    needs: turtlebot3c-pi-gadget-snap
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download gadget snap
        uses: actions/download-artifact@v4
        with:
          name: turtlebot3c-pi-gadget-snap
          path: pi-gadget
      - name: Build the Ubuntu Core image
        run: |
          sudo snap install ubuntu-image --classic
          ubuntu-image snap turtlebot3c.model --snap ./pi-gadget/turtlebot3c-pi_*_arm64.snap
      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: turtlebot3c-ubuntu-image
          path: turtlebot3c.img

